# Generated by Django 4.2.3 on 2026-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True)),
                ('display_leaderboard', models.BooleanField(default=True)),
                ('disable_chronometer', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
