# Generated by Django 4.2.3 on 2026-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_platformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='max_quiz_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
