# Generated by Django 4.2.3 on 2026-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_platformsetting_max_quiz_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='etudiant', max_length=50),
        ),
    ]
