# Generated by Django 4.2.3 on 2026-05-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_question_category'),
        ('adaptive_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveaucompetence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.categorie'),
        ),
    ]
