# Generated by Django 4.2.3 on 2026-05-15 13:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
