# Generated by Django 4.2.3 on 2026-05-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_categorie_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.categorie'),
            preserve_default=False,
        ),
    ]
