# Generated by Django 4.2.3 on 2026-05-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
